name: update figures

on:
  push:
    branches:
      - main
    paths:
      - data/**.csv

  # Enable manual running of workflow, so we can force execution
  workflow_dispatch:

jobs:

  # linting and checking for secrets is only done once
  # no need for multi platform/Python versions.
  basic_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Run pre-commit tests
      run: |
        pip install pre-commit
        pre-commit run --all-files

  generate_figures:
    # only run the figure generation if basic test passes
    needs: basic_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies and run script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python citations_bar_plot_predictions.py data/design_citations.csv 2 --use_weights --output_file_name results/design_citations.svg
        python citations_bar_plot_predictions.py data/notebook_citations.csv 2 --use_weights --output_file_name results/notebook_citations.svg
        python citations_bar_plot_predictions.py data/r_citations.csv 2 --use_weights --output_file_name results/r_citations.svg
    - name: Commit and push
      shell: bash
      run: |
        if ! git diff --quiet; then
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add results/*.svg
          git commit -m "Adding updated svg files."
          git push
        fi

